version: "3.7"
services:
  apache:
    image: rafael01costa/php:7.3-apache 
    container_name: sigef_php
    restart: always
    expose:
      - "80"
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=sigef.localhost
    networks:
      - network
networks:
  network:
    driver: bridge